name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build 
        run: dotnet build -c Release qnap-qsw

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" qnap-qsw-test
