name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test ./...

      - name: Build
        run: go build
